kind: Deployment
apiVersion: apps/v1
metadata:
  name: crash-demo
  namespace: default
  labels:
    k8s-app: crash-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: crash-demo
  template:
    metadata:
      name: crash-demo
      labels:
        k8s-app: crash-demo
    spec:
      containers:
        - name: crash-demo
          image: 'stg609/crash-demo:v0.0.16'
          env:
          - name: DOTNET_gcServer
            value: "0" # 0 表示workstation, 1 表示 server 
          #- name: DOTNET_GCHeapHardLimit  # 设置 GC Heap 允许的大小，超过大小会引起 OOM
          #  value: "1E00000" # 30m
          #- name: DOTNET_GCHighMemPercent  # 设置 怎么样的物理内存占比 需要进行 GC 
          #  value: "0x28" # 40%
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: Logging__LogLevel__Default
            value: Warning
          - name: Logging__LogLevel__Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService
            value: Information
          - name: Logging__LogLevel__Microsoft.Hosting.Lifetime
            value: Information
          livenessProbe:
            httpGet:
              path: /liveness
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 3
          resources:
            requests:
              memory: 1000Mi
              cpu: 1100m
            limits:
              memory: 1000Mi
              cpu: 1100m
          imagePullPolicy: Always